version: '3.8'

services:
  jupyter:
    build: .
    container_name: notebook-viewer
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/project
    environment:
      - JUPYTER_ENABLE_LAB=no
    working_dir: /home/jovyan/project
    command: >
      sh -c "start-notebook.py 
      --NotebookApp.token='' 
      --NotebookApp.password='' 
      --NotebookApp.notebook_dir=/home/jovyan/project"